// Generated by CoffeeScript 1.7.1
(function() {
  module.exports = function(_arg) {
    var basePath, extension, fs, notFoundPage, _ref;
    _ref = _arg != null ? _arg : {}, notFoundPage = _ref.notFoundPage, extension = _ref.extension, basePath = _ref.basePath;
    if (!notFoundPage) {
      notFoundPage = "/404.html";
    }
    if (!extension) {
      extension = "html";
    }
    if (!basePath) {
      basePath = "/public";
    }
    fs = require('fs');
    return function(req, res, next) {
      var fileName, filePath;
      if (req.url === "/") {
        return next();
      }
      if (req.url.lastIndexOf("/") === (req.url.length - 1)) {
        req.url = req.url.slice(0, -1);
      }
      fileName = req.url.split("/").pop();
      if (fileName && fileName.indexOf(".") === -1) {
        req.url += "." + extension;
      }
      filePath = process.cwd() + basePath + req.url;
      return fs.exists(filePath, function(exists) {
        if (!exists) {
          req.url = notFoundPage;
        }
        return next();
      });
    };
  };

}).call(this);
